# Required to run your project under the correct environment.
language: php

env:
  global:
    - "FTP_HOST=ivaldooliveira.esy.es"
    - "FTP_USER=u508509678.ivaldooliveira"
    - "FTP_PASSWORD=.omega.."
    - "FTP_DIRECTORY=/home/u508509678/public_html/"
after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST$FTP_DIRECTORY"

# Versions of PHP you want your project run with.
php:
#  - 5.4
#  - 5.5
#  - 5.6
#  - hhvm
  - 7.0.6

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
#    - php: 5.6
    - php: 7.0.6
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
